### ISSUE TITLE
Error on Debian 11

### ISSUE THREAD

**Issue by lentferj** [NilsKr/JD08PatchManager#1]
I tried to load a backup on Debian 11.8 and got this error:
```
~/git-repos/JD08PatchManager$ python patchmanager.py 
Value not found for defaultdir. Returning default .
Configuration written
File size of /home/lentferj/Dokumente/Roland JD-08/JD08Backup_Factory.svd in Bytes is 2000908
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/lentferj/git-repos/JD08PatchManager/patchmanager.py", line 216, in onBrowse
    self.tryFile(fileName)
  File "/home/lentferj/git-repos/JD08PatchManager/patchmanager.py", line 187, in tryFile
    self.populateList()
  File "/home/lentferj/git-repos/JD08PatchManager/patchmanager.py", line 435, in populateList
    self.patchList.insert('end', self.getPatchNumber(i) + " " + self.getPatchName(data, i))
  File "/home/lentferj/git-repos/JD08PatchManager/patchmanager.py", line 411, in getPatchName
    offs = self.getPatchOffset(data, index)
  File "/home/lentferj/git-repos/JD08PatchManager/patchmanager.py", line 360, in getPatchOffset
    return self.getPatchSectionOffset(data) + 16 + index * 0x800 # 16 is the size of the patch section metadata
  File "/home/lentferj/git-repos/JD08PatchManager/patchmanager.py", line 352, in getPatchSectionOffset
    offs = struct.unpack("l", section[8:12])[0]
struct.error: unpack requires a buffer of 8 bytes
```
```
$ python --version
Python 3.9.2

$ dpkg -l | grep python3-tk
ii  python3-tk:amd64                                            3.9.2-1                          amd64        Tkinter - Writing Tk applications with Python 3.x
```

**Comment by NilsKr** [comment]
Hi Jan,
It looks like for some reason the "l" (lower case L) format specifier in the struct.unpack function takes long to be 8 bytes (64 bits).
Despite having developed this script on a 64 bits (Windows) system, I haven't seen this error.
Can you please try what happens if you replace the "l" in line 352 by "i"?
Thank you,
Nils

**Comment by lentferj** [comment]
Hi Nils,

works :)
But I only tested as far as opening one SVD file.

![grafik](https://github.com/NilsKr/JD08PatchManager/assets/5664183/d1ebd7ff-ad7b-4d44-85c9-80a24480c3b9)

```
diff --git a/patchmanager.py b/patchmanager.py
index 708b022..4bc9693 100644
--- a/patchmanager.py
+++ b/patchmanager.py
@@ -349,7 +349,7 @@ class PatchFile(Frame):
         for i in range(5):
             section = data[i * 16: (i + 1) * 16]
             if section[0:4].decode() == "PATa":
-                offs = struct.unpack("l", section[8:12])[0]
+                offs = struct.unpack("i", section[8:12])[0]
                 #print(f"Found! {offs}")
                 return offs
```

**Comment by NilsKr** [comment]
Thank you kindly for testing this, Jan. Great that it works. I'll commit the change. I'll postpone the creation of a new release for now, as the only change is in the .py script, which can be easily fetched from here separately.
